# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20170924_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='place',
            field=models.CharField(choices=[('M', 'M'), ('T', 'T')], default='M', max_length=255),
        ),
    ]
