# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='to_do',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
