# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20171001_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='to_do',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
