# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20171209_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content_day',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='content_idea',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='content_thought',
            field=models.TextField(blank=True),
        ),
    ]
