# Generated by Django 2.0.3 on 2018-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20180324_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='entries', to='entries.Done'),
        ),
    ]
