# Generated by Django 3.1.3 on 2021-03-02 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20180425_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='complete',
            field=models.BooleanField(blank=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.entry')),
            ],
        ),
    ]
