# Generated by Django 3.2.13 on 2024-10-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_ipaddress_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='complete',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
