# Generated by Django 3.2.13 on 2024-11-19 18:11
# And added a manual migration

from django.db import migrations, models


def from_FK_to_MtM(apps, schema_editor):
    Image = apps.get_model('entries', 'Image')

    for i in Image.objects.all():
        print(i.pk, i.entry.pk)
        i.entry.images.add(i)
        i.entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_auto_20241014_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='entries', to='entries.Image'),
        ),
        migrations.RunPython(from_FK_to_MtM),
        migrations.RemoveField(
            model_name='image',
            name='entry',
        ),
    ]
