# Generated by Django 3.2.13 on 2024-11-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_entry_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Untitled image', max_length=100),
            preserve_default=False,
        ),
    ]
